# Generated by Django 5.2.4 on 2025-08-05 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='tweet',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo', null=True, upload_to='tweets/'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='video',
            field=models.FileField(blank=True, help_text='Optional video', null=True, upload_to='tweets/videos/'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
